### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by tangb** [jaysee/teleInfo#1]
Hi

First of all thanks for sharing your project.

I have trouble compiling your lib:
SoftwareSerial/SoftwareSerial.cpp.o: In function `SoftwareSerial::~SoftwareSerial()':
/usr/share/arduino/libraries/SoftwareSerial/SoftwareSerial.cpp:350: multiple definition of`__vector_3'
MySensors/MyGateway.cpp.o:/home/tang/sketchbook/libraries/MySensors/utility/PinChangeInt.h:172: first defined here
SoftwareSerial/SoftwareSerial.cpp.o: In function `SoftwareSerial::~SoftwareSerial()':
/usr/share/arduino/libraries/SoftwareSerial/SoftwareSerial.cpp:352: multiple definition of`__vector_4'
MySensors/MyGateway.cpp.o:/home/tang/sketchbook/libraries/MySensors/utility/PinChangeInt.h:177: first defined here
SoftwareSerial/SoftwareSerial.cpp.o: In function `SoftwareSerial::~SoftwareSerial()':
/usr/share/arduino/libraries/SoftwareSerial/SoftwareSerial.cpp:352: multiple definition of`__vector_5'
MySensors/MyGateway.cpp.o:/home/tang/sketchbook/libraries/MySensors/utility/PinChangeInt.h:177: first defined here
collect2: error: ld returned 1 exit status

It seems it's a conflict between MySensors lib and SoftwareSerial:
http://forum.mysensors.org/topic/777/software-serial-library

I tryed explained workaround with success (i mean compilation) but it seems teleinfo doesn't work anymore :S
I also used mysensors master branch but my home automation controller only support stable version (1.3, 1.4.X)
Can you explain how you handle this thing?

**Comment by jaysee** [comment]
Yes there is a [know conflict](https://github.com/mysensors/Arduino/issues/63#issuecomment-74045908) between the mysensors-1.4-stable branch and softwareserial, my current working solution is to use the [mysensor-dev](https://github.com/mysensors/Arduino/tree/development) branch that solve this problem.

Seems this dev version still use the 1.4 protocol so it should work with your current controler (mine is OK)

**Comment by tangb** [comment]
Nope i tried development branch and it is 1.5b1 version now.
https://github.com/mysensors/Arduino/blob/development/libraries/MySensors/Version.h
I will try to get a development version just before commit to 1.5b1 ;)

**Comment by jaysee** [comment]
try this one : https://github.com/mysensors/Arduino/tree/f796c677cddf6b9fd78ef4d66318c51d5650a14a, worked for me

**Comment by tangb** [comment]
It works for me too. Thx ;-)

By the way, you say in mysensors.ino that ADPS and PAPP are common fields but in my case they are not available.
It appears those fields are presents only in power panel installed after 2013. Mine was installed near 1999.

Thanks for support.

**Comment by jaysee** [comment]
Thank the notice about ADPS and PAPP, i will had a comment about the possibility of unavailability, as i actually can't detect the presence or not of the fields

your welcome
